name: Build Mod

on:
  push:
    branches: [master]
  
jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Download & Install tModLoader
        run: |
          curl -s -L https://github.com/tModLoader/tModLoader/releases/latest/download/tModLoader.zip -o tModLoader.zip
          unzip -q -o tModLoader.zip -d ../tModLoader
          
      - name: Download & Install .NET Format
        run: dotnet tool install -g dotnet-format

      - name: Create tModLoader.targets file
        shell: bash
        run: |
          cat >> ../tModLoader.targets << EOF
          <Project ToolsVersion="14.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
            <Import Project="tModLoader\tMLMod.targets" />
          </Project>
          EOF

      - name: Reformat mod solution
        run: dotnet format style EndlessEscapade.sln --verify-no-changes

      - name: Build mod solution
        run: dotnet build EndlessEscapade.sln --configuration Release

      - name: Deploy .tmod file artifact
        uses: actions/upload-artifact@v3
        with:
          name: Mod file
          path: EndlessEscapade.tmod

      - name: Deploy action across Discord
        uses: sarisia/actions-status-discord@v1  
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK_DEPLOY }}
          description: |
            Click [here](https://github.com/EndlessEscapade/EndlessEscapade/actions/runs/${{ github.run_id }}) to view full action reports.
