name: Build Endless Escapade

on:
  push:
    branches: [master]
  
jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@master
        with:
          name: tModLoader/tModLoader
          ref: refs/heads/release
    
      - name: Build tModLoader
        run: dotnet build src/tModLoader/Terraria/Terraria.csproj -c Release --nologo -v q -bl;
