name: Build Endless Escapade

on:
  push:
    branches: [master]
  
jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Deploy mod
        uses: sarisia/actions-status-discord@v1  
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK_DEPLOY }}
          description: "Test"
