name: Build Mod

on:
  push:
    branches:
    - stable
  
env:
    TML_PATH_OVERRIDE: ./bin/Saves

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Download & Install tModLoader
        run: |
          curl -s -L https://github.com/tModLoader/tModLoader/releases/latest/download/tModLoader.zip -o tModLoader.zip
          unzip -q -o tModLoader.zip -d ../tModLoader
          rm tModLoader.zip

      - name: Create tModLoader.targets file
        shell: bash
        run: |
          cat >> ../tModLoader.targets << EOF
          <Project ToolsVersion="14.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
            <Import Project="tModLoader\tMLMod.targets" />
          </Project>
          EOF

      - name: Build mod solution
        run: dotnet build EndlessEscapade.sln --configuration Release
        
      - name: Deploy .tmod artifact
        uses: actions/upload-artifact@v3
        with:
          name: EndlessEscapade.tmod
          path: ./bin/Saves/tModLoader/Mods/EndlessEscapade.tmod

      - name: Deploy .dll artifact
        uses: actions/upload-artifact@v3
        with:
          name: EndlessEscapade.dll
          path: ./bin/Release/net6.0/EndlessEscapade.dll

      - name: Deploy action across Discord
        uses: sarisia/actions-status-discord@v1  
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK_DEPLOY }}
          nocontext: true
          title: New version of `Endless Escapade` is ready!
          description: |
            Click [here](https://github.com/EndlessEscapade/EndlessEscapade/actions/runs/${{ github.run_id }}) to view.
